version: '3.8'

services:
  node-red:
    image: nodered/node-red:latest
    container_name: nodered
    environment:
      - TZ=Europe/London  # Change to your local time zone
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    restart: unless-stopped

volumes:
  node_red_data:
